import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/ui/navigationBar";
import { Home, Plus } from "lucide-react";


const roboto = Roboto({
  weight: "400", // Choose appropriate weights
  variable: "--font-roboto",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${geistMono.variable} antialiased`}
      >
      <Navigation />
        {children}
      </body>
    </html>
  );
}
